version: '3.7'

networks:
  odoo_dev:
    driver: bridge

services:
  postgresql:
    image: odoo_dev/postgresql
    container_name: odoo_dev_postgresql
    build:
      context: .
      dockerfile: postgresql/Dockerfile
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    environment:
      - POSTGRES_USER=odoo_user
      - POSTGRES_PASSWORD=superuser_pass 
    volumes:
      - './db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    networks:
      - odoo_dev